import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { firestoreService } from "@/lib/firestore-service";
import PublicNav from "@/components/PublicNav";
import PublicFooter from "@/components/PublicFooter";
import CreatorCard from "@/components/CreatorCard";
import {
  Search, Sparkles, Users, FileText, BarChart3, Wallet,
  ArrowRight, TrendingUp, MousePointerClick, Target,
  Building2, Megaphone, Layers
} from "lucide-react";

export default function Home() {
  const navigate = useNavigate();
  const [creators, setCreators] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    base44.entities.Creator.list("-linkedin_followers", 6)
      .then(setCreators)
      .finally(() => setLoading(false));
  }, []);

  return (
    <div className="min-h-screen bg-white">
      <PublicNav />

      {/* Hero */}
      <section className="relative overflow-hidden bg-gradient-to-b from-sky-50/50 to-white">
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-blue-50 via-transparent to-transparent" />
        <div className="relative max-w-7xl mx-auto px-5 sm:px-6 lg:px-8 pt-20 pb-24 text-center">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-50 text-blue-700 text-xs font-medium mb-6">
            <Sparkles className="w-3.5 h-3.5" />
            3,000+ vetted B2B creators across 100 countries
          </div>
          <h1 className="text-4xl sm:text-5xl lg:text-6xl font-bold text-slate-900 tracking-tight max-w-4xl mx-auto leading-[1.1]">
            The B2B LinkedIn<br />
            <span className="bg-gradient-to-r from-blue-600 to-sky-500 bg-clip-text text-transparent">creator marketplace</span>
          </h1>
          <p className="mt-6 text-lg text-slate-600 max-w-2xl mx-auto leading-relaxed">
            Find the creators your buyers already trust, launch campaigns in days, and track the clicks, leads and pipeline generated by every post.
          </p>
          <div className="mt-8 flex flex-col sm:flex-row items-center justify-center gap-3">
            <button onClick={() => navigate("/signup")} className="w-full sm:w-auto px-6 py-3 rounded-xl bg-slate-900 text-white font-medium hover:bg-slate-800 transition-colors flex items-center justify-center gap-2">
              Launch a campaign
              <ArrowRight className="w-4 h-4" />
            </button>
            <button onClick={() => navigate("/marketplace")} className="w-full sm:w-auto px-6 py-3 rounded-xl border border-slate-200 text-slate-700 font-medium hover:bg-slate-50 transition-colors">
              Browse the marketplace
            </button>
          </div>

          {/* Trust bar */}
          <div className="mt-16">
            <p className="text-xs font-medium text-slate-400 uppercase tracking-wider mb-5">Trusted by modern B2B teams</p>
            <div className="flex flex-wrap items-center justify-center gap-x-8 gap-y-3">
              {["Lemlist", "Attio", "Folk", "Leadbay", "Ringover", "Abyssale"].map((b) => (
                <span key={b} className="text-lg font-semibold text-slate-300">{b}</span>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Three audiences */}
      <section className="py-24 bg-white">
        <div className="max-w-7xl mx-auto px-5 sm:px-6 lg:px-8">
          <div className="text-center mb-14">
            <h2 className="text-3xl sm:text-4xl font-bold text-slate-900 tracking-tight">Built for everyone in the creator economy</h2>
            <p className="mt-4 text-slate-600 max-w-2xl mx-auto">Whether you're running campaigns, managing clients, or creating content — CreatorFlow has you covered.</p>
          </div>
          <div className="grid md:grid-cols-3 gap-6">
            <Link to="/for-companies" className="group bg-blue-50/50 rounded-2xl p-8 border border-blue-100 hover:border-blue-300 hover:shadow-lg transition-all">
              <div className="w-12 h-12 rounded-xl bg-blue-100 flex items-center justify-center mb-5">
                <Building2 className="w-6 h-6 text-blue-600" />
              </div>
              <h3 className="text-xl font-bold text-slate-900 mb-2">For companies</h3>
              <p className="text-sm text-slate-600 leading-relaxed mb-4">Find creators your buyers follow, launch campaigns, and track pipeline attributed to every post.</p>
              <span className="text-sm font-medium text-blue-600 group-hover:text-blue-700 flex items-center gap-1">
                Explore for companies <ArrowRight className="w-4 h-4" />
              </span>
            </Link>
            <Link to="/for-agencies" className="group bg-violet-50/50 rounded-2xl p-8 border border-violet-100 hover:border-violet-300 hover:shadow-lg transition-all">
              <div className="w-12 h-12 rounded-xl bg-violet-100 flex items-center justify-center mb-5">
                <Layers className="w-6 h-6 text-violet-600" />
              </div>
              <h3 className="text-xl font-bold text-slate-900 mb-2">For agencies</h3>
              <p className="text-sm text-slate-600 leading-relaxed mb-4">Manage multiple client campaigns, build shared shortlists, and report on attributed pipeline.</p>
              <span className="text-sm font-medium text-violet-600 group-hover:text-violet-700 flex items-center gap-1">
                Explore for agencies <ArrowRight className="w-4 h-4" />
              </span>
            </Link>
            <Link to="/for-creators" className="group bg-emerald-50/50 rounded-2xl p-8 border border-emerald-100 hover:border-emerald-300 hover:shadow-lg transition-all">
              <div className="w-12 h-12 rounded-xl bg-emerald-100 flex items-center justify-center mb-5">
                <Megaphone className="w-6 h-6 text-emerald-600" />
              </div>
              <h3 className="text-xl font-bold text-slate-900 mb-2">For creators</h3>
              <p className="text-sm text-slate-600 leading-relaxed mb-4">Choose deals from B2B brands, post in your own voice, and get paid within 24 hours.</p>
              <span className="text-sm font-medium text-emerald-600 group-hover:text-emerald-700 flex items-center gap-1">
                Explore for creators <ArrowRight className="w-4 h-4" />
              </span>
            </Link>
          </div>
        </div>
      </section>

      {/* How it works */}
      <section className="py-24 bg-slate-50">
        <div className="max-w-7xl mx-auto px-5 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl sm:text-4xl font-bold text-slate-900 tracking-tight">From brief to pipeline in 5 steps</h2>
            <p className="mt-4 text-slate-600 max-w-2xl mx-auto">Everything you need to run creator-led campaigns that drive measurable demand.</p>
          </div>

          <div className="grid md:grid-cols-5 gap-6">
            {[
              { icon: Search, title: "Find creators", desc: "Search 3,000+ vetted B2B creators matched to your buyers.", num: "01" },
              { icon: FileText, title: "AI brief", desc: "Generate campaign briefs with objectives, guidelines and tracking.", num: "02" },
              { icon: Users, title: "Collaborate", desc: "Creators accept, submit drafts, and you review in one place.", num: "03" },
              { icon: BarChart3, title: "Track results", desc: "See impressions, clicks, leads and pipeline attributed per post.", num: "04" },
              { icon: Wallet, title: "Pay creators", desc: "Automatic payouts handled by CreatorFlow. No admin, no chasing.", num: "05" },
            ].map((step) => (
              <div key={step.num} className="bg-white rounded-2xl p-6 border border-slate-100">
                <div className="text-xs font-bold text-blue-500 mb-3">{step.num}</div>
                <div className="w-11 h-11 rounded-xl bg-blue-50 flex items-center justify-center mb-4">
                  <step.icon className="w-5 h-5 text-blue-600" />
                </div>
                <h3 className="font-semibold text-slate-900 mb-2">{step.title}</h3>
                <p className="text-sm text-slate-500 leading-relaxed">{step.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Featured creators */}
      <section className="py-24 bg-white">
        <div className="max-w-7xl mx-auto px-5 sm:px-6 lg:px-8">
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between mb-10 gap-4">
            <div>
              <h2 className="text-3xl font-bold text-slate-900 tracking-tight">Featured creators</h2>
              <p className="mt-2 text-slate-600">A curated selection from our B2B creator marketplace.</p>
            </div>
            <Link to="/marketplace" className="text-sm font-medium text-blue-600 hover:text-blue-700 flex items-center gap-1">
              View all creators <ArrowRight className="w-4 h-4" />
            </Link>
          </div>

          {loading ? (
            <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">
              {[...Array(6)].map((_, i) => (
                <div key={i} className="bg-white rounded-2xl border border-slate-200 p-5 animate-pulse">
                  <div className="flex items-center gap-3 mb-4">
                    <div className="w-12 h-12 rounded-full bg-slate-200" />
                    <div className="space-y-2 flex-1">
                      <div className="h-3 bg-slate-200 rounded w-24" />
                      <div className="h-2 bg-slate-200 rounded w-32" />
                    </div>
                  </div>
                  <div className="h-16 bg-slate-100 rounded-lg" />
                </div>
              ))}
            </div>
          ) : (
            <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">
              {creators.map((c) => (
                <CreatorCard key={c.id} creator={c} />
              ))}
            </div>
          )}
        </div>
      </section>

      {/* Stats */}
      <section className="py-24 bg-slate-50">
        <div className="max-w-7xl mx-auto px-5 sm:px-6 lg:px-8">
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-8 text-center">
            {[
              { value: "5M+", label: "Impressions generated" },
              { value: "30K+", label: "Leads generated" },
              { value: "3,000+", label: "Creators on CreatorFlow" },
              { value: "5K+", label: "Posts published" },
            ].map((s) => (
              <div key={s.label}>
                <p className="text-4xl lg:text-5xl font-bold text-slate-900 tracking-tight">{s.value}</p>
                <p className="mt-2 text-sm text-slate-500">{s.label}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Case study highlight */}
      <section className="py-24 bg-slate-900 text-white">
        <div className="max-w-5xl mx-auto px-5 sm:px-6 lg:px-8">
          <div className="grid md:grid-cols-2 gap-12 items-center">
            <div>
              <span className="text-xs font-medium text-blue-400 uppercase tracking-wider">Case study</span>
              <h2 className="mt-3 text-3xl font-bold tracking-tight">How BlogSEO turned creator content into product signups</h2>
              <p className="mt-4 text-slate-400 leading-relaxed">
                BlogSEO briefed SEO & SaaS creators on LinkedIn, then traced every trial back to the post that drove it — all in CreatorFlow.
              </p>
              <div className="mt-8 grid grid-cols-3 gap-6">
                <div>
                  <p className="text-2xl font-bold">9</p>
                  <p className="text-xs text-slate-400 mt-1">creators activated</p>
                </div>
                <div>
                  <p className="text-2xl font-bold">2,940</p>
                  <p className="text-xs text-slate-400 mt-1">qualified clicks</p>
                </div>
                <div>
                  <p className="text-2xl font-bold">512</p>
                  <p className="text-xs text-slate-400 mt-1">trials started</p>
                </div>
              </div>
            </div>
            <div className="bg-slate-800 rounded-2xl p-8 border border-slate-700">
              <div className="space-y-4">
                {[
                  { icon: TrendingUp, label: "Attributed pipeline", value: "€48.2K", change: "+24%" },
                  { icon: MousePointerClick, label: "Qualified clicks", value: "418", change: "+18%" },
                  { icon: Target, label: "Leads generated", value: "124", change: "+31%" },
                ].map((m) => (
                  <div key={m.label} className="flex items-center justify-between p-4 bg-slate-700/50 rounded-xl">
                    <div className="flex items-center gap-3">
                      <div className="w-9 h-9 rounded-lg bg-blue-500/20 flex items-center justify-center">
                        <m.icon className="w-4 h-4 text-blue-400" />
                      </div>
                      <span className="text-sm text-slate-300">{m.label}</span>
                    </div>
                    <div className="text-right">
                      <p className="font-semibold">{m.value}</p>
                      <p className="text-xs text-emerald-400">{m.change}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-24 bg-gradient-to-b from-white to-sky-50">
        <div className="max-w-3xl mx-auto px-5 sm:px-6 lg:px-8 text-center">
          <h2 className="text-3xl sm:text-4xl font-bold text-slate-900 tracking-tight">Your next creator campaign starts here</h2>
          <p className="mt-4 text-slate-600">Get a clear creator strategy, campaign format and estimated budget for your next launch.</p>
          <div className="mt-8 flex flex-col sm:flex-row items-center justify-center gap-3">
            <button onClick={() => navigate("/signup")} className="w-full sm:w-auto px-6 py-3 rounded-xl bg-slate-900 text-white font-medium hover:bg-slate-800 transition-colors">
              Start for free
            </button>
            <button onClick={() => navigate("/pricing")} className="w-full sm:w-auto px-6 py-3 rounded-xl border border-slate-200 text-slate-700 font-medium hover:bg-white transition-colors">
              See pricing
            </button>
          </div>
          <p className="mt-4 text-xs text-slate-400">Free to join · No credit card required · Cancel anytime</p>
        </div>
      </section>

      <PublicFooter />
    </div>
  );
}